### ISSUE TITLE
NPE while tearing down Mojarra runtime

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4093]
When stopping a web application where Faces is enabled, a NPE is thrown:
2015-12-26 21:40:37,333 ERROR [Gogo shell] jsf.config - Unexpected exception when attempting to tear down the Mojarra runtime
java.lang.NullPointerException
at com.sun.faces.context.ApplicationMap.get(ApplicationMap.java:97)
at com.sun.faces.application.ApplicationAssociate.getInstance(ApplicationAssociate.java:350)
at com.sun.faces.el.ELUtils.getDefaultExpressionFactory(ELUtils.java:912)
at com.sun.faces.config.ConfigureListener.contextDestroyed(ConfigureListener.java:348)
at osgi.extender.web.servlet.OurServletContext.lambda$6(OurServletContext.java:151)
at osgi.extender.web.servlet.OurServletContext.lambda$25(OurServletContext.java:714)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
#### Affected Versions
[2.2.9, 2.3.0-m04]

**Comment by mnriem** [comment]
For Mojarra 2.3 and earlier please contact your vendor for support (RedHat, IBM, Oracle, Omnifish, Payara, etceteras)
