### ISSUE TITLE
Buffer size doesn't support -1

### ISSUE THREAD

**Issue by ren-zhijun-oracle** [eclipse-ee4j/mojarra#4116]
JSF spec says:

> javax.faces.FACELETS_BUFFER_SIZE – The buffer size to set on the response when the ResponseWriter is generated. By default the value is 1024\. A value of -1 will not assign a buffer size on the response.

Setting the option value to -1 results in exceptions when rendering:

```
16:01:00,355 ERROR [application] (default task-11) Error Rendering View[/views/SomeView.xhtml]: java.lang.NegativeArraySizeException
	at com.sun.faces.application.view.WriteBehindStateWriter.<init>(WriteBehindStateWriter.java:92)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:421)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:133)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at javax.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:337)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:120)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:219)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:647)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
```

Looking further:

```
protected ResponseWriter createResponseWriter(FacesContext context)
throws IOException {

	...

	if (responseBufferSizeSet) {
		// set the buffer for content 		extContext.setResponseBufferSize(responseBufferSize);
	}
```

This doesn't take -1 into account too, servlets wouldn't understand it.
Plus it seemingly wouldn't apply the default Mojarra's buffer size, when it's not set explicitly, which appears to be another problem.

com.sun.faces.resourceBufferSize could use a fix in the same vein.

-1 is useful because it means using servlets'/server's default. With Wildfly 8.2.0 and Undertow 1.1.8 the default would be to use a direct memory buffer pool. Mojarra doesn't support -1, resulting in a new direct memory buffer allocation for each response, which is a performance problem.
#### Environment
Wildfly 8.2.0
#### Affected Versions
[2.2.8-01]

**Comment by mnriem** [comment]
This issue was filed against a version that is not maintained by the Eclipse Mojarra project. Ask your vendor for a fix on this specific version. If this bug exists in the current version of Mojarra please open a new issue, add a reproducer and if you can create a PR fixing the issue
