### ISSUE TITLE
NPE when determining converter for primitive values

### ISSUE THREAD

**Issue by codylerum** [eclipse-ee4j/mojarra#4500]
On Version 2.3.5 when the backing bean value is a primitive (int, boolean, etc)  there is a NPE during the validation phase.

This is a regression from 2.2

```xhtml
<h:selectOneMenu value="#{billingAccountView.billingAccount.commissionable}">
   <f:selectItem itemValue="true" itemLabel="Yes" />
   <f:selectItem itemValue="false" itemLabel="No" />
</h:selectOneMenu>
```

Where billingAccountView.billingAccount.commissionable is a primitive boolean

```java
15:27:04,781 SEVERE [javax.enterprise.resource.webcontainer.jsf.renderkit] (default task-2) Could not instantiate converter for type boolean: java.lang.NullPointerException
15:27:04,781 SEVERE [javax.enterprise.resource.webcontainer.jsf.renderkit] (default task-2) : java.lang.NullPointerException
	at com.sun.faces.cdi.CdiUtils.createConverter(CdiUtils.java:125)
	at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:1458)
	at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:425)
	at org.omnifaces.cdi.converter.ConverterManager.createConverter(ConverterManager.java:155)
	at org.omnifaces.cdi.converter.ConverterManager$Proxy$_$$_WeldClientProxy.createConverter(Unknown Source)
	at org.omnifaces.application.OmniApplication.createConverter(OmniApplication.java:98)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getConvertedValue(HtmlBasicInputRenderer.java:127)
	at com.sun.faces.renderkit.html_basic.MenuRenderer.convertSelectOneValue(MenuRenderer.java:194)
	at com.sun.faces.renderkit.html_basic.MenuRenderer.getConvertedValue(MenuRenderer.java:341)
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1122)
	at javax.faces.component.UIInput.validate(UIInput.java:1030)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1334)
	at javax.faces.component.UIInput.processValidators(UIInput.java:757)
	at javax.faces.component.UISelectOne.processValidators(UISelectOne.java:207)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1298)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1298)
	at javax.faces.component.UIForm.processValidators(UIForm.java:269)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1298)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1298)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1298)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1332)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:77)
````

**Comment by manfredriem** [comment]
Can you attach a reproducer which only uses core Mojarra? Thanks!

**Comment by codylerum** [comment]
@manfredriem reproducer coming shortly. This only happens if JSF 2.3 is enabled like so.
```java
@ApplicationScoped
@FacesConfig(version = FacesConfig.Version.JSF_2_3)
public class Jsf23Activator {

}```

**Comment by codylerum** [comment]
@manfredriem 

Here is a reproducer  https://github.com/codylerum/jsf-demos/tree/master/converter-npe

http://localhost:8080/demo on wildfly-14.0.1.Final

Just click execute and the NPE will trigger.

**Comment by codylerum** [comment]
If anyone else runs into this then adding Omnifaces 3.3 (currently snapshot) is a workaround

**Comment by prince-jn** [comment]
This a major issue. I cannot use primitive type with cdi enable.

Any idea when this will be fixed?

**Comment by michaelmpschubert** [comment]
Issue still persists. After activating JSF 2.3 with marker class "@FacesConfig @ApplicationScoped public class Jsf23Activator { //... }" I am no longer able to use boolean value from JPA Entity with PrimeFaces in *.xhtml (Code: <p:inputSwitch id="activeUser" value="#{operatorBean.operator.active}" />).
Any command in *.xhtml page results in NPE. And I need JSF 2.3 with CDI to inject DataAccessObjects into @FacesConverter. 
Major issue.

**Comment by codylerum** [comment]
This is still an issue with 2.3.9

@arjantijms do you know if this has been addressed anywhere in the later builds?

Not being able to use primitives seems like a rather large issue.

**Comment by tandraschko** [comment]
@codylerum AFAIK the mojarra team doesn't have much time currently. Maybe you can provide a PR to make it easier for them.

**Comment by manfredriem** [comment]
As Mojarra is now at Eclipse you all are the team! ;)

**Comment by open-gdsn** [comment]
Seems to also happen with `List<String>` : https://stackoverflow.com/questions/57947555/multiple-autocomplete-with-a-value-of-a-list-of-strings-cant-generate-converter

**Comment by ineszetter** [comment]
Happening also with **int type**. The omnifaces workaround worked like a charm by adding 
converter="omnifaces.SelectItemsConverter" instead of an ejb converter.
