### ISSUE TITLE
NPE on enabled primefaces.CLIENT_SIDE_VALIDATION 

### ISSUE THREAD

**Issue by azizjonachilov** [eclipse-ee4j/mojarra#4634]
Hi,

I've an application in JSF 2.3 running on Payara Server 5.184. On migrating to Payara Server version 5.193 I've encountered error:

> java.lang.NullPointerException
	at com.sun.faces.cdi.CdiUtils.createConverter(CdiUtils.java:102)
	at com.sun.faces.application.applicationimpl.InstanceFactory.createConverter(InstanceFactory.java:481)
	at com.sun.faces.application.ApplicationImpl.createConverter(ApplicationImpl.java:510)
	at javax.faces.application.ApplicationWrapper.createConverter(ApplicationWrapper.java:431)
	at org.primefaces.util.ComponentUtils.getConverter(ComponentUtils.java:163)
	at org.primefaces.renderkit.CoreRenderer.renderValidationMetadata(CoreRenderer.java:659)
	at org.primefaces.component.selectbooleancheckbox.SelectBooleanCheckboxRenderer.encodeInput(SelectBooleanCheckboxRenderer.java:124)
	at org.primefaces.component.selectbooleancheckbox.SelectBooleanCheckboxRenderer.encodeMarkup(SelectBooleanCheckboxRenderer.java:86)
	at org.primefaces.component.selectbooleancheckbox.SelectBooleanCheckboxRenderer.encodeEnd(SelectBooleanCheckboxRenderer.java:60)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:595)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1654)

which does not occur in version 5.184. It seams, that an error in   Mojarra 2.3.9.payara-p3.

Sample project is: https://github.com/azizjonachilov/java

By disabling primefaces.CLIENT_SIDE_VALIDATION, no NPE occurred. Thank you.

**Comment by dmatej** [comment]
Duplucates #500 fixed in 2.3.10

**Comment by melloware** [comment]
@arjantijms This issue is safe to close it was resolved in 2.3.10

**Comment by arjantijms** [comment]
Thanks! I'll close it indeed then.
