### ISSUE TITLE
Use of ui:repeat varStatus.index as an array index fails

### ISSUE THREAD

**Issue by Edwardiv1** [eclipse-ee4j/mojarra#4947]
This code works in Jakarta Faces 2.3.14, but fails in 2.3.15 and 2.3.16:

```
<f:metadata>
  <f:viewParam name="fid" value="#{myForm}" converter="#{formsConverter}" />
  <f:viewAction action="#{myForm.init}" />
</f:metadata>
...

<ui:repeat var="q" value="#{myForm.questions}" varStatus="stat">
      <tr><td>#{stat.index+1}.</td>
        <td><h:outputText value="#{q}" /></td>
        <td><h:selectOneRadio group="q#{stat.index}" value="#{myForm.answers[stat.index]}" 
 required="true" label="Question #{stat.index}" >
      <f:selectItem itemValue="1" />
...
```

The part that fails is `value="#{myForm.answers[stat.index]}"`.  When I try to submit the form in Jakarta Faces 2.3.15, it throws the following exception:

```
org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [Faces Servlet] in context with path [/MyApp] threw exception [/forms/my-form.xhtml @43,117 value="#{myForm.answers[stat.index]}": Target Unreachable, [null] returned null] with root cause
javax.el.PropertyNotFoundException: Target Unreachable, [null] returned null
	at org.apache.el.parser.AstValue.getTarget(AstValue.java:119)
	at org.apache.el.parser.AstValue.getType(AstValue.java:58)
	at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:174)
	at org.jboss.weld.module.web.el.WeldValueExpression.getType(WeldValueExpression.java:93)
	at com.sun.faces.facelets.el.TagValueExpression.getType(TagValueExpression.java:62)
	at com.sun.faces.renderkit.html_basic.HtmlBasicInputRenderer.getConvertedValue(HtmlBasicInputRenderer.java:74)
	at com.sun.faces.renderkit.html_basic.MenuRenderer.convertSelectOneValue(MenuRenderer.java:146)
	at com.sun.faces.renderkit.html_basic.MenuRenderer.getConvertedValue(MenuRenderer.java:208)
	at javax.faces.component.UIInput.getConvertedValue(UIInput.java:1106)
	at javax.faces.component.UIInput.validate(UIInput.java:1011)
	at javax.faces.component.UIInput.executeValidate(UIInput.java:1318)
	at javax.faces.component.UIInput.processValidators(UIInput.java:733)
	at javax.faces.component.UISelectOne.processValidators(UISelectOne.java:183)
	at com.sun.faces.facelets.component.UIRepeat.process(UIRepeat.java:568)
	at com.sun.faces.facelets.component.UIRepeat.processValidators(UIRepeat.java:849)
	at javax.faces.component.UIForm.processValidators(UIForm.java:229)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
	at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:921)
	at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:1310)
	at com.sun.faces.lifecycle.ProcessValidationsPhase.execute(ProcessValidationsPhase.java:53)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:76)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:177)
	at javax.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:707)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:451)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:667)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

I've tried initializing `answers` in both `@PostConstruct` and also a viewAction, but still get the same error. If I access `answers` using a hard-coded number, e.g. `answers[0]`, there is no error. The error only occurs with `answers[stat.index]`

I'm wondering if this is a regression or if the spec doesn't allow the use of varStatus.index as an array index, in which case I need to find a new way of doing it.

Bean code:
```
@Named @ViewScoped
public class MyForm {
  protected String[] answers = new String[42];

  @PostConstruct
  public void init() {
    answers = new String[42];
    Arrays.fill(answers, "");
  }

...
}
```

I'm using tomcat 9.0.45

**Comment by BalusC** [comment]
It's difficult to create an unambiguous reproducer for your issue. That `<f:viewParam>` on a managed bean didn't make much sense to me.

The following full reproducer works just fine for me in Mojarra 2.3.17 on Tomcat 9.0.56 in the smallest possible project with everything configured to the absolute minimum (i.e. web.xml, faces-config.xml and beans.xml files are basically empty).

View:
```
<!DOCTYPE html>
<html
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
>
    <h:body>
        <h:form id="form">
            <ui:repeat id="list1" value="#{bean.list1}" varStatus="loop">
                <h:inputText id="input" value="#{bean.list2[loop.index]}" />
            </ui:repeat>
            <h:commandButton value="Submit" />
            <h:outputText id="output" value="#{bean.list2}" />
        </h:form>
    </h:body>
</html>
```

Model:
```
package com.example;

import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

@Named
@RequestScoped
public class Bean {

    private List<String> list1;
    private List<String> list2;

    @PostConstruct
    public void init() {
        list1 = Arrays.asList("one", "two", "three");
        list2 = Arrays.asList(null, null, null);
    }
    
    public List<String> getList1() {
        return list1;
    }
    
    public List<String> getList2() {
        return list2;
    }
}
```

**Comment by Edwardiv1** [comment]
I haven't tested it with 2.3.17, but I worked around it by using `<c:forEach />` instead of `<ui:repeat />`
Regarding your test case, not sure if it makes a difference, but I was using ViewScoped (not RequestScoped) and String[] (not List<String>).

In any event, I'm happy for this to be closed because the workaround works well.

**Comment by BalusC** [comment]
Closing off as norepro.
