### ISSUE TITLE
Incorrect "CDI is not available" IllegalStateException is thrown 

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/mojarra#5080]
**Describe the bug**
https://github.com/eclipse-ee4j/mojarra/commit/808d9edc832045353585aa177a59d7c49f224784 changed to expect a CDI BeanManager to always be available but due to CDI 4.0 changes, that is now wrong which is explained in https://eclipse-ee4j.github.io/cdi/2021/10/25/way-to-cdi4.html:
```
Change of Default Empty beans.xml Discovery Mode

One notable change coming to CDI is the [discovery mode of bean archives containing empty beans.xml](https://github.com/eclipse-ee4j/cdi/issues/500). These were formerly treated as explicit bean archives (i.e. having discovery mode all) but beginning with CDI 4.0, they will be considered as implicit bean archives (discovery mode annotated).

In other words, if a class in such an archive is to be recognized as a bean, it needs to have at least one bean defining annotation. It can be a breaking change which is why this change also comes with a backward compatible switch - all CDI Full products have to contain an option that switches the behavior to how it worked in the past. The option is of course a temporary measure to ease transition and applications are encouraged to adapt their bean archives accordingly in the long term.
```

In summary, with Jakarta EE 9 (CDI 3.0), most applications had an CDI Bean Manager available unless they configured to disable CDI (discovery mode == none).  With CDI 4.0, the default is discovery mode == none, so I think we need to check if the CDI bean manager is available again, instead of assuming it is.

The exception that we currently see is:
```
[2022-04-24T08:45:06.998+0000] [glassfish 7.0] [INFO] [faces.config.listener.version] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=80 _ThreadName=AutoDeployer] [timeMillis: 1650789906998] [levelValue: 800] [[
  Initializing Mojarra 4.0.0-M6 for context '/ejblite_nointerface_descriptor_ejblitejsf_vehicle_web']]

[2022-04-24T08:45:07.089+0000] [glassfish 7.0] [SEVERE] [] [jakarta.enterprise.resource.webcontainer.faces.config] [tid: _ThreadID=80 _ThreadName=AutoDeployer] [timeMillis: 1650789907089] [levelValue: 1000] [[
  Critical error during deployment:
java.lang.IllegalStateException: CDI is not available
        at com.sun.faces.util.Util.getCdiBeanManager(Util.java:1493)
        at com.sun.faces.el.ELUtils.addCDIELResolver(ELUtils.java:192)
        at com.sun.faces.el.ELUtils.buildFacesResolver(ELUtils.java:164)
        at com.sun.faces.application.ApplicationAssociate.initializeELResolverChains(ApplicationAssociate.java:416)
        at com.sun.faces.application.applicationimpl.ExpressionLanguage.performOneTimeELInitialization(ExpressionLanguage.java:144)
        at com.sun.faces.application.applicationimpl.ExpressionLanguage.getELResolver(ExpressionLanguage.java:89)
        at com.sun.faces.application.ApplicationImpl.getELResolver(ApplicationImpl.java:200)
        at com.sun.faces.el.ELContextImpl.<init>(ELContextImpl.java:60)
        at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:202)
        at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:5051)
        at com.sun.enterprise.web.WebModule.contextListenerStart(WebModule.java:563)
        at org.apache.catalina.core.StandardContext.start(StandardContext.java:5627)
        at com.sun.enterprise.web.WebModule.start(WebModule.java:511)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:877)
        at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:144)
        at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:134)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:858)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2021)
        at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1667)
        at com.sun.enterprise.web.WebApplication.start(WebApplication.java:82)
        at org.glassfish.internal.data.EngineRef.start(EngineRef.java:98)
        at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:267)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:328)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:480)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:199)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/javax.security.auth.Subject.doAs(Subject.java:361)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
        at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:140)
        at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:573)
        at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:460)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:388)
        at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:379)
        at org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:209)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

**To Reproduce**

Run the Jakarta EE 10 Platform TCK with the ejb30.lite.nointerface.descriptor tests, I'll update this with a full description after I have recreated it locally (currently, we have seen it with Jenkins).

**Comment by scottmarlow** [comment]
I'm closing this due to Faces 4.0 SPEC having a hard requirement that all Faces 4.0 application deployments to be configured to enable CDI.  We will deal with that in the Platform TCK, at least that is now the plan.
