### ISSUE TITLE
Jakarta EE 10 Platform TCK + Faces test failure: GlassFish 7 (with Mojarra 4.0.0-M7-RELEASE) is throwing com.sun.faces.application.view.ViewHandlingStrategyNotFoundException during com.sun.faces.application.view.MultiViewHandler.getViewDeclarationLanguage() call

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/mojarra#5084]
**Describe the bug**

Jakarta EE 10 [Platform TCK test results ](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1779/artifact/ejb30_lite_appexception-results.tar.gz) shows the below failure.  

[2022-05-03T12:21:43.003+0000] [glassfish 7.0] [WARNING] [] [jakarta.enterprise.web] [tid: _ThreadID=30 _ThreadName=http-listener-1(3)] [timeMillis: 1651580503003] [levelValue: 900] [[
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
com.sun.faces.application.view.ViewHandlingStrategyNotFoundException
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at com.sun.faces.application.view.ViewHandlingStrategyManager.getStrategy(ViewHandlingStrategyManager.java:57)
	at com.sun.faces.application.view.ViewDeclarationLanguageFactoryImpl.getViewDeclarationLanguage(ViewDeclarationLanguageFactoryImpl.java:45)
	at com.sun.faces.application.view.MultiViewHandler.getViewDeclarationLanguage(MultiViewHandler.java:407)
	at jakarta.faces.application.ViewHandlerWrapper.getViewDeclarationLanguage(ViewHandlerWrapper.java:335)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:179)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:95)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:275)
	at org.apache.catalina.security.SecurityUtil$1.run(SecurityUtil.java:273)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/javax.security.auth.Subject.doAsPrivileged(Subject.java:550)
	at org.apache.catalina.security.SecurityUtil.execute(SecurityUtil.java:308)
	at org.apache.catalina.security.SecurityUtil.doAsPrivilege(SecurityUtil.java:166)
	at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1572)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:119)
	at org.apache.catalina.core.StandardPipeline.doInvoke(StandardPipeline.java:611)
	at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:550)
	at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:75)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:121)
	at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:294)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:187)
	at com.sun.enterprise.v3.services.impl.ContainerMapper$HttpHandlerCallable.call(ContainerMapper.java:440)
	at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:144)
	at org.glassfish.grizzly.http.server.HttpHandler.runService(HttpHandler.java:174)
	at org.glassfish.grizzly.http.server.HttpHandler.doHandle(HttpHandler.java:153)
	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:196)
	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:246)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:178)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:118)
	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:96)
	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
	at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**

1. 	# become root user (so GlassFish can use root ports)
2. 	su
3. 	mkdir -p /tmp/ee10
4.     cd /tmp/ee10
5.     export WORKSPACE=$PWD
6. 	# [ -z "$ANT_HOME" ] && wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.zip && unzip -o apache-ant-1.10.6-bin.zip && rm -f apache-ant-1.10.6-bin.zip && export ANT_HOME=$PWD/apache-ant-1.10.6 && export PATH=$ANT_HOME/bin
8.   export GF_BUNDLE_URL=https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip
9.    [ ! -d "jakartaeetck" ] && wget https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip && unzip jakarta-jakartaeetck-10.0.0.zip && chmod +x jakartaeetck/docker/run_jakartaeetck.sh
10. bash -x ./jakartaeetck/docker/run_jakartaeetck.sh ejb30/lite/appexception/singleton/annotated 2>&1 | tee tck.log
11.  See error in tck.log by searching for `ejblitejsf.*FAILED`

**Comment by scottmarlow** [comment]
Closing as https://jakarta.ee/specifications/faces/4.0/ has:
```
Removing deprecated things:
-     Removing JSP support as a VDL (deprecated since 2.0) - [FACES #1546](https://github.com/eclipse-ee4j/faces-api/issues/1546)
```

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/common/vehicle/ejblitejsf/ejblitejsf_vehicle.jsp#L26
