### ISSUE TITLE
UnsupportedOperationException in 4.0 on startup

### ISSUE THREAD

**Issue by tandraschko** [eclipse-ee4j/mojarra#5198]
```
com.sun.faces.config.ConfigurationException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
        at com.sun.faces.config.manager.Documents.getXMLDocuments(Documents.java:104)
        at com.sun.faces.config.ConfigManager.initialize(ConfigManager.java:311)
        at com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:179)
        at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1045)
        at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624)
        at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:982)
        at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740)
        at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392)
```

you can simply replicate when cloning PrimeFaces:
- mvn clean install -DskipTests
- cd primefaces-integration-tests-jakarta
- mvn clean package jetty:run -Pmojarra-4.0

and the exception is thrown on startup

**Comment by tandraschko** [comment]
Could be the same as: https://github.com/eclipse-ee4j/mojarra/pull/5195

**Comment by christophs78** [comment]
I´m able to confirm https://github.com/eclipse-ee4j/mojarra/pull/5195 fixes this issue.
(I checked out this PR, built it and successful run primefaces-integration-tests-jakarta.)

**Comment by BalusC** [comment]
Okay.
