### ISSUE TITLE
ArrayIndexOutOfBoundsException during restore state

### ISSUE THREAD

**Issue by pizzi80** [eclipse-ee4j/mojarra#5269]
**Describe the bug**

If `ViewExpiredException` is thrown inside an action 
the restoreState throws an `ArrayIndexOutOfBoundsException`

**To Reproduce**

```
<h:form id="test" >
    <h:commandButton id="expired" action="#{testErrors.throwViewExpiredException}" value="JSF Expired" />
</h:form>
```

```
@Named
@RequestScoped
public class TestErrors {

    public void throwViewExpiredException() {
		throw new ViewExpiredException();
	}

}
```

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
	at jakarta.faces.component.UIComponentBase.restoreState(UIComponentBase.java:1223)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.lambda$restoreView$1(FaceletPartialStateManagementStrategy.java:360)
	at com.sun.faces.component.visit.FullVisitContext.invokeVisitCallback(FullVisitContext.java:125)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1266)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at com.sun.faces.application.view.FaceletPartialStateManagementStrategy.restoreView(FaceletPartialStateManagementStrategy.java:349)
	at com.sun.faces.application.view.ViewHandlingStrategy.restoreView(ViewHandlingStrategy.java:90)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.restoreView(FaceletViewHandlingStrategy.java:256)
	at com.sun.faces.application.view.MultiViewHandler.restoreView(MultiViewHandler.java:129)
	at jakarta.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:96)
	at jakarta.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:96)
	at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:128)
	at jakarta.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:96)
	at com.sun.faces.lifecycle.RestoreViewPhase.execute(RestoreViewPhase.java:161)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:95)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:159)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:691)
	... 29 more
```

**Desktop (please complete the following information):**

 - OS: Fedora 38
 - Version Faces **4.0.2** or  **master**

**Comment by BalusC** [comment]
Norepro. I'm also wondering how exactly to reproduce it. The restore view is normally invoked BEFORE invoke application.

**Comment by BalusC** [comment]
This exception is usually thrown when component is used by multiple requests. I.e. in a threadunsafe way. More than often because it's via `binding` attribute referenced in a bean with a scope greater than request.
