### ISSUE TITLE
Mojarra 4.0.3 is not Faces compatible as it fails the `com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapper*` tests

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/mojarra#5308]
**Describe the bug**

We need a Mojarra 4.0.4 release that passes the following Jakara Faces TCK tests that currently fail with Mojarra 4.0.3:
```
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetApplicationTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetAttributesEmptyTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetAttributesTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetClientIdsWithMessagesEmptyTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetClientIdsWithMessagesTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetELContextTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetExceptionHandlerTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetExternalContextTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetMaximumSeverityTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetMessageListByIdTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetMessageListTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetMessagesEmptyTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetPartialViewContextTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetRenderKitTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetResponseCompleteTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperGetViewRootTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperIsGetProcessingEventTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperIsPostbackTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperIsReleasedTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperIsValidationFailedTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperRenderResponseTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperSetExceptionHandlerTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperSetGetCurrentPhaseIdTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperSetGetResponseStreamTest
[INFO]      [exec] [javatest.batch] FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperSetGetResponseWriterTest
```

**To Reproduce**
Run https://ci.eclipse.org/jakartaee-tck/job/jakarta-faces-old-tck-glassfish/ against https://www.eclipse.org/downloads/download.php?file=/ee4j/glassfish/glassfish-7.0.8.zip which includes Mojarra 4.0.3.  Example the started https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish and search for `com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapper`

**Additional context**

Also see recent comments on https://github.com/eclipse-ee4j/glassfish/pull/24556

**Comment by scottmarlow** [comment]
More test output from the first test failure:
```
[INFO]      [exec] [javatest.batch] Beginning Test:  com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] 
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  Harness - harness.executeMode is set to "2"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  Harness - keywords (to be passed to tests) set to:  all
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  Harness - sClassPathFromExecProps = 
[INFO]      [exec] [javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd CLASSPATH=:/opt/tools/java/openjdk/jdk-17/17.0.2+8/lib/rt.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/tsharness.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/jsftck.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/sigtest.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/javatest.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../classes:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/cdi-api.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/jakarta.servlet.jsp.jstl-api.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/jakarta.inject.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/jakarta.faces.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/jakarta.servlet.jsp-api.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/jakarta.servlet-api.jar;/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/target/glassfish7/glassfish/modules/expressly.jar::/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-logging-1.1.3.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-io-2.4.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-lang3-3.12.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-codec-1.9.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-collections-3.2.1.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/commons-httpclient-3.1.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/cssparser-0.9.25.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/dec-0.1.2.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/htmlunit-2.66.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/htmlunit-core-js-2.66.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/htmlunit-cssparser-1.12.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/htmlunit-xpath-2.66.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/httpcore-4.4.9.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/httpclient-4.5.5.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/httpmime-4.5.5.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/neko-htmlunit-2.66.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/nekohtml-1.9.21.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/sac-1.3.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/saxpath.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/jaxen-1.1.6.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/jaxen-core-1.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/jdom-1.1.3.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/xercesImpl-2.11.0.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/xalan-2.7.2.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/serializer-2.7.2.jar:/home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../lib/xml-apis-1.4.01.jar: HOME=/home/jenkins windir= SYSTEMROOT= /opt/tools/java/openjdk/jdk-17/17.0.2+8/bin/java com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient -p /home/jenkins/agent/workspace/10/jakarta-faces-tck-glassfish/download/faces-tck-4.0.2/tck/old-tck/run/target/faces-tck/bin/xml/../../tmp/tstest.jte -t facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] ************************************************************
[INFO]      [exec] [javatest.batch] * props file set to "/tmp/jenkins-cts-props.txt"
[INFO]      [exec] [javatest.batch] ************************************************************
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: #######  Value of harness.socket.retry.count is "10"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: #######  Value of harness.log.port is "12000"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: #######  Actual bind value of harness.log.port is "12000"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: *** in EETest.run(argv,p)
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: TESTCLASS=com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ** IN getRunMethod: testClass=com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ** IN getRunMethod: testname=facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ** GOT RUN METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: **runmethod=facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ABOUT TO GET SETUP METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: No setupMethod annotation present
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: getSetupMethod - checking for testcase specific setup method:  facesCtxWrapperAddGetMessagesTest_setup
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: getSetupMethod - checking for default class specific setup method
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: GOT SETUP METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: No cleanupMethod annotation present
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: getCleanupMethod - checking for testcase specific cleanup method:  facesCtxWrapperAddGetMessagesTest_cleanup
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: getCleanupMethod - checking for default class specific cleanup method
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: GOT CLEANUP METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ABOUT TO INVOKE SETUP METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  [BaseUrlClient] Test setup OK
[INFO]      [exec] [javatest.batch] REQUEST LINE: GET /jsf_ctx_facesctxwrap_web/TestServlet?testname=facesCtxWrapperAddGetMessagesTest HTTP/1.0
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: INVOKED SETUP METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ABOUT TO INVOKE EETEST RUN METHOD!
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [HttpRequest] Added request header: User-Agent: JavaServer Faces TCK/2.2
[INFO]      [exec] [javatest.batch] 
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [BaseUrlClient] EXECUTING
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  [HttpRequest] Dispatching request: 'GET /jsf_ctx_facesctxwrap_web/TestServlet?testname=facesCtxWrapperAddGetMessagesTest HTTP/1.0' to target server at 'localhost:18080'
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: ########## The real value set: false
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - >> "GET /jsf_ctx_facesctxwrap_web/TestServlet?testname=facesCtxWrapperAddGetMessagesTest HTTP/1.0[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - >> "User-Agent: JavaServer Faces TCK/2.2[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - >> "Host: localhost:18080[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - >> "[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "HTTP/1.1 500 Internal Server Error[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "Content-Language: [\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "Content-Type: text/html[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "Connection: close[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "Content-Length: 1611[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "[\r][\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Eclipse GlassFish 7.0.9 - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Internal Server Error</h1><hr/><p><b>type</b> Exception report</p><p><b>message</b>Internal Server Error</p><p><b>description</b>The server encountered an internal error that prevented it from fulfilling this request.</p><p><b>exception</b> <pre>org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001318: Cannot resolve an ambiguous dependency between: [\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "  - com.sun.faces.cdi.FacesContextProducer@22f718c8,[\n]"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - << "  - Managed Bean [class com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.TestServlet$TCKFacesContext] with qualifiers [@Any @Default]</pre></p><p><b>note</b> <u>The full stack traces of the exception and its root causes are available in the Eclipse GlassFish 7.0.9 logs.</u></p><hr/><h3>Eclipse GlassFish 7.0.9</h3></body></html>"
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  TRACE: [WIRE] - HttpConnectionManager is null.  Connection cannot be released.
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  ERROR: [WebValidatorBase] Unexpected '500' received from target server!
[INFO]      [exec] [javatest.batch] Error response recieved from server:
[INFO]      [exec] [javatest.batch] ------------------------------------------------
[INFO]      [exec] [javatest.batch] <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Eclipse GlassFish 7.0.9 - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 500 - Internal Server Error</h1><hr/><p><b>type</b> Exception report</p><p><b>message</b>Internal Server Error</p><p><b>description</b>The server encountered an internal error that prevented it from fulfilling this request.</p><p><b>exception</b> <pre>org.jboss.weld.exceptions.AmbiguousResolutionException: WELD-001318: Cannot resolve an ambiguous dependency between: 
[INFO]      [exec] [javatest.batch]   - com.sun.faces.cdi.FacesContextProducer@22f718c8,
[INFO]      [exec] [javatest.batch]   - Managed Bean [class com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.TestServlet$TCKFacesContext] with qualifiers [@Any @Default]</pre></p><p><b>note</b> <u>The full stack traces of the exception and its root causes are available in the Eclipse GlassFish 7.0.9 logs.</u></p><hr/><h3>Eclipse GlassFish 7.0.9</h3></body></html>
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  ERROR: Test case throws exception: [BaseUrlClient] facesCtxWrapperAddGetMessagesTest failed! Check output for cause of failure.
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  ERROR: Exception at:  
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  ERROR: com.sun.ts.tests.common.webclient.TestFailureException: Test FAILED!
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.tests.common.webclient.WebTestCase.execute(WebTestCase.java:180)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.tests.common.webclient.BaseUrlClient.invoke(BaseUrlClient.java:456)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient.facesCtxWrapperAddGetMessagesTest(URLClient.java:73)
[INFO]      [exec] [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]      [exec] [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[INFO]      [exec] [javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO]      [exec] [javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:337)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient.run(URLClient.java:41)
[INFO]      [exec] [javatest.batch] 	at com.sun.ts.tests.jsf.api.jakarta_faces.context.facescontextwrapper.URLClient.main(URLClient.java:33)
[INFO]      [exec] [javatest.batch] 
[INFO]      [exec] [javatest.batch] 09-06-2023 00:47:40:  [BaseUrlClient] Test cleanup OK
[INFO]      [exec] [javatest.batch] STATUS:Failed.Test case throws exception: [BaseUrlClient] facesCtxWrapperAddGetMessagesTest failed! Check output for cause of failure.
[INFO]      [exec] [javatest.batch] Failed. Test case throws exception: [BaseUrlClient] facesCtxWrapperAddGetMessagesTest failed! Check output for cause of failure.
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] Finished Test:  FAILED........com/sun/ts/tests/jsf/api/jakarta_faces/context/facescontextwrapper/URLClient.java#facesCtxWrapperAddGetMessagesTest
[INFO]      [exec] [javatest.batch] ********************************************************************************
[INFO]      [exec] [javatest.batch] Number of tests completed:  4697 (4696 passed, 1 failed, 0 with errors)

```

**Comment by jamezp** [comment]
I haven't yet tested this, but the stack traces lead to https://github.com/eclipse-ee4j/mojarra/pull/5207 being the cause of the failures.

**Comment by scottmarlow** [comment]
> I haven't yet tested this, but the stack traces lead to #5207 being the cause of the failures.

I ran against a Mojarra local snapshot build (using WildFly) that has every `4.0.3` change except the #5207 change.  

I cannot explain why I did see 143 (different) tests failing due to `java.lang.ClassNotFoundException: com.gargoylesoftware.htmlunit.WebClient`.  However, the facescontextwrapper tests passed when I ran with #5207 reverted.  Could this mean that further changes are needed to complement the #5207 change?

For reference the complete list of facescontextwrapper tests that are failing with 4.0.3 are listed in https://gist.github.com/scottmarlow/4c7c121470398cafcbf697195ed119fe

**Comment by arjantijms** [comment]
The ant based scripts for running the TCKs are essentially al setup the same way. We just found similar issues with the connector TCK runner inside GlassFish. 

See https://github.com/eclipse-ee4j/glassfish/pull/24568/commits/82fc12b9ae930f3c8f64d6f2008889d6035c45a2

@BalusC can you take a look at the https://github.com/eclipse-ee4j/mojarra/pull/5207 change? I'll take a look soon as well.
