### ISSUE TITLE
4.0.4: Server side generated UITreeNode lost after updating Tree (Primefaces)

### ISSUE THREAD

**Issue by brivalin** [eclipse-ee4j/mojarra#5317]
**Describe the bug**

After generating a Tree component server side, with its UITreeNode childrens. The tree is well-generated.
But when I update the Tree bound in @RequestScoped bean, it loses UITreeNode childrens previously created for Tree.

Original Report : [https://github.com/primefaces/primefaces/issues/8916](https://github.com/eclipse-ee4j/mojarra/issues/url)

**To Reproduce**

Reproducer: [mojarra-tree-reproducer.zip](https://github.com/eclipse-ee4j/mojarra/files/12669625/mojarra-tree-reproducer.zip)

1. Run mvn clean jetty:run -Pmojarra40
2. Navigate to http://127.0.0.1:8080/primefaces-test
3. Click on "Update" button
4. See log error and tree nodes disappears

```
GRAVE: Error Rendering View[/test.xhtml]
jakarta.faces.FacesException: Unsupported tree node type:type1
	at org.primefaces.component.tree.Tree.getUITreeNodeByType(Tree.java:100)
	at org.primefaces.component.tree.TreeRenderer.encodeTreeNode(TreeRenderer.java:673)
	at org.primefaces.component.tree.TreeRenderer.encodeTreeNodeChildren(TreeRenderer.java:818)
	at org.primefaces.component.tree.TreeRenderer.encodeVerticalTree(TreeRenderer.java:413)
	at org.primefaces.component.tree.TreeRenderer.encodeMarkup(TreeRenderer.java:354)
	at org.primefaces.component.tree.TreeRenderer.encodeEnd(TreeRenderer.java:265)
	at jakarta.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:585)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1442)
	at jakarta.faces.render.Renderer.encodeChildren(Renderer.java:146)
	at jakarta.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:556)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
	at com.sun.faces.context.PartialViewContextImpl$PhaseAwareVisitCallback.visit(PartialViewContextImpl.java:595)
	at com.sun.faces.component.visit.PartialVisitContext.invokeVisitCallback(PartialVisitContext.java:158)
	at jakarta.faces.component.UIForm.visitTree(UIForm.java:354)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at jakarta.faces.component.UIComponent.visitTree(UIComponent.java:1278)
	at com.sun.faces.context.PartialViewContextImpl.processComponents(PartialViewContextImpl.java:393)
	at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:308)
	at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:65)
	at jakarta.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1086)
	at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
	at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:422)
	at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:163)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
	at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:72)
	at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:178)
	at jakarta.faces.webapp.FacesServlet.executeLifecyle(FacesServlet.java:692)
	at jakarta.faces.webapp.FacesServlet.service(FacesServlet.java:449)
	at org.eclipse.jetty.servlet.ServletHolder$NotAsync.service(ServletHolder.java:1410)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
	at org.eclipse.jetty.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:170)
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:202)
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1635)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:527)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:131)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:223)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:149)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Expected behavior**

Mojarra doesn't loose UITreeNode childrens when updating Tree. (Like MyFaces)

**Desktop (please complete the following information):**

 - OS: [ALL]
 - Browser [ALL]
 - Version [ALL]

**Smartphone (please complete the following information):**

 - Device: [ALL]
 - OS: [ALL]
 - Browser [ALL]
 - Version [ALL]

**Additional context**

It fails with Mojarra 4.0.4 but works with MyFaces 4.0.1.

`mvn clean jetty:run -Pmojarra40` (fails)

`mvn clean jetty:run -Pmyfaces40` (passes)

**Comment by mnriem** [comment]
@brivalin Can you create a PR fixing the issue?

**Comment by mnriem** [comment]
@brivalin A reproducer without PrimeFaces in the mix would be helpful too

**Comment by BalusC** [comment]
This is not entirely the correct approach. You populate the components only during postconstruct of the view scope instead of during every request. See also among others https://stackoverflow.com/q/3510614

Edit your XHTML to add a `postAddToView` listener.
```
<p:tree id="tree" value="#{testView.root}">
   <f:event type="postAddToView" listener="#{testView.populate}" />
</p:tree>
```
Split the component tree populating logic from your `init()` into `populate()` as follows:
```
@PostConstruct
public void init() {
    generateNodes();
}

public void populate(ComponentSystemEvent event) {
    Tree tree = (Tree) event.getComponent();
    tree.setVar("data");
    tree.getChildren().addAll(generateUiNodes());
}
```
