### ISSUE TITLE
Duplicate component ID for PrimeFaces tree component when using jakarta.faces.PARTIAL_STATE_SAVING=false

### ISSUE THREAD

**Issue by jOlliv** [eclipse-ee4j/mojarra#5536]
**Describe the bug**

With disabled partial state saving the child components of PrimeFaces tree component are added twice to the component tree. This leads to the error "duplicate component ID" at state saving. This only occurs with Mojarra 4.0, but not with MyFaces 4.0. So it seems to be a problem at Mojarra.

The logged error is:
```
Dec 05, 2024 3:57:55 PM com.sun.faces.util.Util checkIdUniqueness
SEVERE: JSF1007: Duplicate component ID j_idt8:j_idt10:j_idt11 found in view.
Dec 05, 2024 3:57:55 PM com.sun.faces.util.Util checkIdUniqueness
SEVERE: +id: j_id1
 type: jakarta.faces.component.UIViewRoot@4971bc3c
 [...]
    +id: j_idt8
     type: jakarta.faces.component.html.HtmlForm@1a91ba79
      +id: j_idt9
       type: 
            <div class="card">
                <h5 style="margin-top:0">Client</h5>
                
      +id: j_idt10
       type: org.primefaces.component.tree.Tree@3884f3b1
        +id: j_idt11  <===============
         type: org.primefaces.component.tree.UITreeNode@18a0fe84
          +id: j_idt12
           type: jakarta.faces.component.html.HtmlOutputText@679d6d66
        +id: j_idt11  <===============
         type: org.primefaces.component.tree.UITreeNode@7048419e
          +id: j_idt12
           type: jakarta.faces.component.html.HtmlOutputText@6f4e2d5d
      +id: j_idt13
       type: 
            </div>
  [...]

Dec 05, 2024 3:57:55 PM com.sun.faces.context.AjaxExceptionHandlerImpl handlePartialResponseError
SEVERE: java.lang.IllegalStateException: Component ID j_idt8:j_idt10:j_idt11 has already been found in the view.  
java.lang.IllegalStateException: Component ID j_idt8:j_idt10:j_idt11 has already been found in the view.  
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1200)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.util.Util.checkIdUniqueness(Util.java:1189)
        at com.sun.faces.application.view.FaceletFullStateManagementStrategy.saveView(FaceletFullStateManagementStrategy.java:655)
        at jakarta.faces.application.StateManager.getViewState(StateManager.java:243)
        at com.sun.faces.context.PartialViewContextImpl.renderState(PartialViewContextImpl.java:523)
        at com.sun.faces.context.PartialViewContextImpl.processPartial(PartialViewContextImpl.java:315)
        at org.primefaces.context.PrimePartialViewContext.processPartial(PrimePartialViewContext.java:61)
        at jakarta.faces.component.UIViewRoot.encodeChildren(UIViewRoot.java:1092)
        at jakarta.faces.component.UIComponent.encodeAll(UIComponent.java:1435)
        at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:422)
        at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:160)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
        at jakarta.faces.application.ViewHandlerWrapper.renderView(ViewHandlerWrapper.java:125)
        at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:93)
  [...]
```

**To Reproduce**

The attached reproducer is the "Tree Basic" example from PrimeFaces showcase with 'jakarta.faces.PARTIAL_STATE_SAVING=false' configuration in web.xml.

[primefaces-tree-partial-state-saving-reproducer.zip](https://github.com/user-attachments/files/18026726/primefaces-tree-partial-state-saving-reproducer.zip)

1. mvn clean jetty:run -Pmojarra40
2. Go to 'http://localhost:8080/'
3. Expand node "Documents" under section "Ajax and No Border"
4. See error in console: SEVERE: JSF1007: Duplicate component ID j_idt8:j_idt10:j_idt11 found in view.

**Expected behavior**

No error should occur while expanding the node when running on Mojarra, as it is on MyFaces (`mvn clean jetty:run -Pmyfaces40`).

**Comment by BalusC** [comment]
Duplicates https://github.com/eclipse-ee4j/mojarra/issues/5233

FSS is deprecated in Faces 4.1 and subject for removal.

Please use PSS instead. If PSS is causing problems please open ticket about that instead.
